# fly.toml app configuration file generated for bun-todo on 2023-09-11T21:33:32+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bun-todo"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
